# Site settings
title: Driving Poverty
email: hattierowan@gmail.com
url: http://harrietrowan.github.io/driving-poverty
description: "An explainer about how driver's license suspension policies amplify inequality."

baseurl: http://harrietrowan.github.io/driving-poverty

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Harriet Rowan

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/HattieRowan
  - title: github
    url: https://github.com/HarrietRowan

# Build settings
markdown: kramdown
permalink: pretty
